# Generated by Django 5.2.5 on 2026-04-27 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('poster', models.ImageField(upload_to='movies/', verbose_name='Постер')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя героя')),
                ('photo', models.ImageField(blank=True, upload_to='characters/', verbose_name='Фото героя')),
                ('description', models.TextField(verbose_name='Описание героя')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='main.movie', verbose_name='Фильм')),
            ],
        ),
    ]
