# Generated by Django 5.2.5 on 2026-04-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('game', 'Игра')], default='movie', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='character',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='main.movie', verbose_name='Проект (фильм/игра/сериал)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
