# Generated by Django 5.2.5 on 2026-04-27 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movie_category_alter_character_movie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок (н-р: Сюжет или Миссии)')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='main.movie', verbose_name='Проект')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
