# Generated by Django 5.2.5 on 2026-04-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_extrainfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='extrainfo',
            options={'ordering': ['order'], 'verbose_name': 'Доп. информация', 'verbose_name_plural': 'Доп. информация'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Укажи число от 1 до 10', verbose_name='Твоя оценка (1-10)'),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('planned', 'В планах'), ('watching', 'В процессе'), ('completed', 'Завершено/Пройдено')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='movie',
            name='verdict',
            field=models.TextField(blank=True, help_text='Краткий итог: стоит ли оно того?', verbose_name='Твой личный вердикт'),
        ),
        migrations.AlterField(
            model_name='character',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='main.movie', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/', verbose_name='Скриншот')),
                ('caption', models.CharField(blank=True, max_length=100, verbose_name='Подпись (необязательно)')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='main.movie', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
            },
        ),
    ]
